### ISSUE TITLE
Implement references to other GUN nodes

### ISSUE THREAD

**Issue by dougwhitehead** [ChronosX88/JGUN#1]
Gun is supposed to allow arbitrary graphs with cycles, etc. But currently one can not link to a node elsewhere in the tree.  For example, I would expect the following to work.

gun = new Gun....
PathRef itemRef = gun.get("inventory").get("item");
itemRef.get("12").put( new JSONObject().put("name","eggs")).await();
itemRef.get("dozen").put( itemRef.get("12") );

In other words, the graph should look like:

```
gun ---> "inventory" ---> "item"  -*-----> "12" ----*-> { "name":"eggs" }
                                    \--> "dozen" --/
```

**Comment by ChronosXYZ** [comment]
Fixed with recent commits.
