### ISSUE TITLE
Problem with NodeRef chaining

### ISSUE THREAD

**Issue by dougwhitehead** [ChronosX88/JGUN#5]
Test case to be attached.  There are two tests, they should act the same, but they return different results.

[BasicsTest.zip](https://github.com/ChronosX88/JGUN/files/3687956/BasicsTest.zip)

**Comment by dougwhitehead** [comment]
oops I left an import to beanutils in the sample, just delete the import and it should work

**Comment by ChronosXYZ** [comment]
Fixed with recent commits.
